package com.example.engine

import com.example.data.model.*

data class ScenePreset(
    val id: String,
    val titleEn: String,
    val titleAr: String,
    val descriptionEn: String,
    val descriptionAr: String,
    val state: SceneState
)

object ScenePresets {
    val presets: List<ScenePreset> = listOf(
        ScenePreset(
            id = "riyadh_cafe_mirror",
            titleEn = "Riyadh Cafe Mirror Selfie",
            titleAr = "سيلفي مرآة بمقهى الرياض",
            descriptionEn = "Chest-level mirror reflection in a modern cafe with warm pendant lighting and authentic thobe creases.",
            descriptionAr = "انعكاس مرآة بمستوى الصدر في مقهى عصري، مع إضاءة دافئة وتجعدات ثوب طبيعية.",
            state = SceneState(
                captureType = CaptureType.MIRROR_SELFIE,
                sceneContext = SceneContext.CAFE_CONTEMPORARY,
                culturalFidelity = CulturalFidelity.SAUDI_AUTHENTIC,
                timeOfDay = TimeOfDay.INDOOR_WARM_AMBIENT,
                gender = Gender.MALE,
                ageGroup = AgeGroup.LATE_20S,
                identityAnchor = "Saudi young man with neat groomed beard, expressive dark brown eyes, confident relaxed expression",
                expression = Expression.SLIGHT_SMIRK,
                hairStyle = HairStyle.MODERN_TAPERED_SHORT,
                clothingType = ClothingType.WHITE_COTTON_THOBE,
                bodyPose = BodyPose.STANDING_NATURAL,
                supportSurface = SupportSurface.MARBLE_FLOOR,
                cameraAngle = CameraAngle.CHEST_LEVEL_MIRROR,
                cameraDistance = CameraDistance.MEDIUM_PORTRAIT,
                lensType = LensType.SMARTPHONE_26MM_MAIN,
                pitchDeg = -4,
                yawDeg = 2,
                leftHand = HandState.IN_POCKET,
                rightHand = HandState.HOLDING_PHONE,
                lightingSource = LightingSource.CAFE_PENDANT_LAMPS,
                lightDirection = LightDirection.FRONT_45_KEY,
                colorTempK = 2700,
                shadowHardnessPercent = 40,
                enableSensorNoise = true,
                enableEdgeSoftness = true,
                enableSubtleBarrelDistortion = true,
                targetModel = TargetModel.CHATGPT_DALL_E_3,
                seed = 718294L
            )
        ),
        ScenePreset(
            id = "majlis_tea_session",
            titleEn = "Majlis Floor Seating Tea Session",
            titleAr = "مجلس تقليدي بفرش أرضي",
            descriptionEn = "Cross-legged floor seating on Sadu cushions with realistic body depression, dallah, and tea cup in hand.",
            descriptionAr = "تربيعة أرضية على مساند السدو مع انضغاط فيزيائي للوزن، ودلة وفنجان شاي باليد.",
            state = SceneState(
                captureType = CaptureType.THIRD_PERSON,
                sceneContext = SceneContext.MAJLIS_TRADITIONAL,
                culturalFidelity = CulturalFidelity.SAUDI_AUTHENTIC,
                timeOfDay = TimeOfDay.INDOOR_WARM_AMBIENT,
                gender = Gender.MALE,
                ageGroup = AgeGroup.MID_30S,
                identityAnchor = "Saudi man in mid-30s with warm candid smile, distinctive Gulf facial features",
                expression = Expression.NATURAL_WARM_SMILE,
                hairStyle = HairStyle.COVERED_SHEMAGH_AGAL,
                clothingType = ClothingType.WHITE_COTTON_THOBE,
                bodyPose = BodyPose.SITTING_FLOOR_MAJLIS,
                supportSurface = SupportSurface.FLOOR_MAJLIS_CUSHION,
                cameraAngle = CameraAngle.EYE_LEVEL,
                cameraDistance = CameraDistance.MEDIUM_PORTRAIT,
                lensType = LensType.PORTRAIT_35MM,
                pitchDeg = 0,
                yawDeg = 5,
                leftHand = HandState.RESTING_ON_LAP,
                rightHand = HandState.HOLDING_HOT_COFFEE,
                lightingSource = LightingSource.MAJLIS_CEILING_CHANDELIER,
                lightDirection = LightDirection.DIFFUSE_FRONTAL,
                colorTempK = 3000,
                shadowHardnessPercent = 35,
                enableSensorNoise = true,
                targetModel = TargetModel.CHATGPT_DALL_E_3,
                seed = 938472L
            )
        ),
        ScenePreset(
            id = "car_passenger_golden_hour",
            titleEn = "Car Passenger Golden Hour Selfie",
            titleAr = "سيلفي راكب السيارة وقت الغروب",
            descriptionEn = "Arm's-length selfie inside car cabin with warm 3200K side window sunbeams and contoured leather seats.",
            descriptionAr = "سيلفي بمدى الذراع داخل كابينة السيارة مع أشعة شمس الغروب النافذة ومقاعد جلدية محيطة.",
            state = SceneState(
                captureType = CaptureType.SUBJECT_HELD_SELFIE,
                sceneContext = SceneContext.CAR_PASSENGER,
                culturalFidelity = CulturalFidelity.SAUDI_AUTHENTIC,
                timeOfDay = TimeOfDay.GOLDEN_HOUR,
                gender = Gender.MALE,
                ageGroup = AgeGroup.EARLY_20S,
                identityAnchor = "Young Saudi man with modern haircut, slight friendly smile, candid road trip energy",
                expression = Expression.NATURAL_WARM_SMILE,
                hairStyle = HairStyle.TEXTURED_CURLS,
                clothingType = ClothingType.CASUAL_POLO_JEANS,
                bodyPose = BodyPose.SEATED_IN_CAR,
                supportSurface = SupportSurface.CAR_LEATHER_SEAT,
                cameraAngle = CameraAngle.SLIGHT_HIGH_ANGLE,
                cameraDistance = CameraDistance.ARMS_LENGTH,
                lensType = LensType.SMARTPHONE_24MM_WIDE,
                pitchDeg = 14,
                yawDeg = -6,
                leftHand = HandState.RESTING_ON_LAP,
                rightHand = HandState.HOLDING_PHONE,
                lightingSource = LightingSource.LOW_GOLDEN_SUN,
                lightDirection = LightDirection.HARD_SIDE_LIGHT,
                colorTempK = 3200,
                shadowHardnessPercent = 55,
                enableSensorNoise = false,
                enableSubtleBarrelDistortion = true,
                enableWindowHighlightBlowout = true,
                targetModel = TargetModel.CHATGPT_DALL_E_3,
                seed = 349182L
            )
        ),
        ScenePreset(
            id = "street_candid_residential",
            titleEn = "Saudi Residential Street Candid",
            titleAr = "لقطة عفوية بشارع سكني",
            descriptionEn = "Mid-stride walk in a quiet neighborhood with carport shades and authentic late-afternoon sun.",
            descriptionAr = "مشي طبيعي في حي هادئ مع مظلات السيارات وأشعة شمس العصر المائلة.",
            state = SceneState(
                captureType = CaptureType.THIRD_PERSON,
                sceneContext = SceneContext.RESIDENTIAL_STREET,
                culturalFidelity = CulturalFidelity.SAUDI_AUTHENTIC,
                timeOfDay = TimeOfDay.GOLDEN_HOUR,
                gender = Gender.MALE,
                ageGroup = AgeGroup.MID_30S,
                identityAnchor = "Saudi man walking with confident natural stride, thoughtful candid expression",
                expression = Expression.THOUGHTFUL_CANDID,
                hairStyle = HairStyle.COVERED_SHEMAGH_AGAL,
                clothingType = ClothingType.WHITE_COTTON_THOBE,
                bodyPose = BodyPose.WALKING_STREET,
                supportSurface = SupportSurface.CONCRETE_TILES,
                cameraAngle = CameraAngle.EYE_LEVEL,
                cameraDistance = CameraDistance.FULL_BODY,
                lensType = LensType.PORTRAIT_35MM,
                pitchDeg = 0,
                yawDeg = 0,
                leftHand = HandState.IN_POCKET,
                rightHand = HandState.HOLDING_TASBEEH,
                lightingSource = LightingSource.LOW_GOLDEN_SUN,
                lightDirection = LightDirection.FRONT_45_KEY,
                colorTempK = 3300,
                shadowHardnessPercent = 50,
                enableSensorNoise = true,
                targetModel = TargetModel.CHATGPT_DALL_E_3,
                seed = 582103L
            )
        )
    )
}
